FROM clojure:lein-2.8.1-alpine

RUN adduser -S -D -h /nonexistent -H service_user

RUN apk --no-cache add libwebp libwebp-tools imagemagick bash

ADD public/brokenImage.jpg /public/brokenImage.jpg
ADD bin/thumbnail /thumbnail
ADD target/vignette-standalone.jar /vignette.jar

EXPOSE 8080

USER service_user

ENTRYPOINT ["java"]
CMD ["-Xmx1024m", "-server", "-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.authenticate=false", "-Dcom.sun.management.jmxremote.ssl=false", "-jar", "/vignette.jar", "-m", "s3", "-p", "8080", "-C"]
