apiVersion: v1
kind: Service
metadata:
  labels:
    app: vignette
  name: vignette
  namespace: prod
spec:
  ports:
  - port: 80
    name: main
    protocol: TCP
    targetPort: 8080
  selector:
    app: vignette
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vignette
    stage: deployed
  name: vignette
  namespace: prod
spec:
  selector:
    matchLabels:
      app: vignette
      stage: deployed
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  progressDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app: vignette
        stage: deployed
    spec:
      containers:
      - name: vignette
        image: artifactory.wikia-inc.com/vignette:0.3
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: STORAGE_ACCESS_KEY
          value: 3DLQ430ZD2A2YG2258ND
        - name: STORAGE_SECRET_KEY
          value: rLwxTDcwJ4d1gTDZ15AUCk8p8UKHz1e2TPGC2zKo
        - name: STORAGE_ENDPOINT
          value: http://dfs
        - name: STORAGE_PROXY
          value: prod.dfs.service.sjc.consul
        - name: STORAGE_PROXY_PORT
          value: "80"
        - name: LOGGER_TYPE
          value: syslog
        - name: LOGGER_FILE_OUTPUT
          value: /tmp/vignette.log
        - name: LOGGER_APPLICATION
          value: vignette
        - name: IMAGEMAGICK_BASE
          value: /usr
        - name: VIGNETTE_THUMBNAIL_BIN
          value: /thumbnail
        - name: GETOPT
          value: /bin/getopt
        - name: TIMEOUT
          value: timeout
        - name: TIMEOUT_TIME
          value: "-t 30"
        - name: GIF2WEBP
          value: /usr/bin/gif2webp
        - name: WIKIA_ENVIRONMENT
          value: prod
        - name: WIKIA_DATACENTER
          value: sjc
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 0.1
            memory: 1024Mi
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  labels:
    app: vignette
  name: vignette
  namespace: prod
spec:
  rules:
  - host: prod.k8s.wikia.net
    http:
      paths:
      - path: /vignette
        backend:
          serviceName: vignette
          servicePort: 80
  - host: prod.sjc.k8s.wikia.net
    http:
      paths:
      - path: /vignette
        backend:
          serviceName: vignette
          servicePort: 80
