apiVersion: v1
kind: Service
metadata:
  labels:
    app: vignette-test
  name: vignette-test
  namespace: dev
spec:
  ports:
  - port: 80
    name: main
    protocol: TCP
    targetPort: 8080
  selector:
    app: vignette-test
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vignette-test
    stage: deployed
  name: vignette-test
  namespace: dev
spec:
  selector:
    matchLabels:
      app: vignette-test
      stage: deployed
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  progressDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app: vignette-test
        stage: deployed
    spec:
      containers:
      - name: vignette-test
        image: ${IMAGE_PATH}
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: STORAGE_ACCESS_KEY
          value: 6J1ZCE0KZZYG2U9CHJGA
        - name: STORAGE_SECRET_KEY
          value: gpCJjIptrr5S7XOGYG2bH4yXnru+YN/O7hBNyPyf
        - name: STORAGE_ENDPOINT
          value: http://dfs
        - name: STORAGE_PROXY
          value: dev.dfs.service.poz-dev.consul
        - name: STORAGE_PROXY_PORT
          value: "80"
        - name: LOGGER_TYPE
          value: syslog
        - name: LOGGER_FILE_OUTPUT
          value: /tmp/vignette.log
        - name: LOGGER_APPLICATION
          value: vignette
        - name: IMAGEMAGICK_BASE
          value: /usr
        - name: VIGNETTE_THUMBNAIL_BIN
          value: /thumbnail
        - name: VIGNETTE_BROKEN_IMAGE
          value: /public/brokenImage.jpg
        - name: GETOPT
          value: /bin/getopt
        - name: TIMEOUT
          value: timeout
        - name: TIMEOUT_TIME
          value: "-t 30"
        - name: GIF2WEBP
          value: /gif2webp
        - name: WIKIA_ENVIRONMENT
          value: dev
        - name: WIKIA_DATACENTER
          value: poz
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 0.1
            memory: 1024Mi
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  labels:
    app: vignette-test
  name: vignette-test
  namespace: dev
spec:
  rules:
  - host: poz-dev.k8s.wikia.net
    http:
      paths:
      - path: /vignette-test
        backend:
          serviceName: vignette-test
          servicePort: 80
  - host: dev.poz-dev.k8s.wikia.net
    http:
      paths:
      - path: /vignette-test
        backend:
          serviceName: vignette-test
          servicePort: 80
