(ns vignette.util.regex)

(def revision-regex #"\d+|latest")
(def wikia-regex #"[\w-\.]+")
(def top-dir-regex #"\w")
(def middle-dir-regex #"\w\w")
(def original-regex #"[^/]*")
(def adjustment-mode-regex #"\w+")
(def thumbnail-mode-regex #"[\w-]+")
(def size-regex #"\d+")
(def size-regex-allow-negative #"-{0,1}\d+")
(def image-type-regex #"\/images|\/avatars|")
(def uuid-regex #"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
